import os
import sys
import time
from rich.console import Console
from rich.panel import Panel
from dotenv import load_dotenv

# Add parent to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

load_dotenv()

from orchestrator import AgentOrchestrator

# Force ASCII for legacy windows terminals
console = Console(force_terminal=False, width=100)

def run_god_mode():
    """
    ⚡ GOD MODE: AUTOMATED RESEARCH PIPELINE
    """
    
    # Using simple prints to avoid Unicode/Spinner issues on Windows
    print("\n" + "="*80)
    print("  GOD MODE: AUTOMATED RESEARCH PIPELINE")
    print("  Processing all papers and building semantic memory")
    print("="*80 + "\n")

    # Initialize Orchestrator
    provider = os.getenv("LLM_PROVIDER", "openrouter")
    print(f"[*] Initializing Agents... (Provider: {provider})\n")
    
    orchestrator = AgentOrchestrator({
        "llm_provider": provider,
        "api_key": (os.getenv("OPENROUTER_API_KEY") or os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")),
        "db_url": os.getenv("DATABASE_URL", "sqlite:///research_metadata.db"),
        "vector_db_path": os.getenv("VECTOR_DB_PATH", "./faiss_research_db"),
        "pdf_folder": os.getenv("PDF_FOLDER", "./my_papers"),
    })

    # Step 1: Mass Ingestion
    pdf_folder = os.getenv("PDF_FOLDER", "./my_papers")
    papers = [f for f in os.listdir(pdf_folder) if f.lower().endswith(".pdf")]
    
    print(f"\n[*] Found {len(papers)} papers. Starting mass ingestion...")
    
    print("[WORKING] Ingesting & Indexing... (This may take a few minutes)")
    
    # Run orchestrator ingestion
    try:
        results = orchestrator.ingest_documents(pdf_folder)
        print(f"\n[SUCCESS] Indexed {results['total_files']} files, {results['total_chunks']} chunks into memory.")
    except Exception as e:
        console.print(f"\n[bold red][ERROR] Ingestion failed:[/bold red] {str(e)}")
        return

    # Step 2: Global Knowledge Synthesis
    print("\n[*] Generating God Mode Global Report...")
    print("[WORKING] The Analyst is synthesizing all data across 18 documents...")
    
    query = "Summarize the overarching goals, technical architecture, and implementation roadmap across all papers. Focus on how everything connects into one platform."
    
    try:
        master_report = orchestrator.analyze(query, top_k=15)
        
        # Save report
        report_path = "GOD_MODE_MASTER_REPORT.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("# God Mode: Master Research Report\n\n")
            f.write(f"**Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**Sources:** {len(papers)} Documents Provided\n")
            f.write(f"**Agent System:** {provider.upper()} ({os.getenv('OPENROUTER_MODEL', 'google/gemini-2.0-flash-001')})\n\n")
            f.write("---\n")
            f.write(f"\n{master_report}\n")
            f.write("\n\n---\n*Generated by the Multi-Agent Research System (God Mode Pipeline)*")

        print(f"\n[SUCCESS] GOD MODE COMPLETE!")
        print(f"📄 Master report saved to: {report_path}")
        print("\n[INFO] Dashboard is now populated. Refresh http://localhost:5173 to see results.")
    except Exception as e:
        print(f"\n[ERROR] Analysis failed: {e}")

if __name__ == "__main__":
    run_god_mode()
